# Generated by Django 6.0.1 on 2026-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_user_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
